export default {
  "totalPhone":6,
  "dataList":[
    {
      "id": "id",
      "name": "机型",
      "createTime": "上市时间",
      "purchesMoney":"购买价格",
      "appearance":"外观设计",
      "color":"手机颜色",
      "type":"手机类型",
      "phoneSize":"手机尺寸",
      "weight":"手机重量",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "hwList":[
    {
      "id": "1",
      "name": "华为mate40 pro",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "2",
      "name": "华为2",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "oppoList":[
    {
      "id": "3",
      "name": "OPPO",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "4",
      "name": "OPPO1",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "vivoList":[
    {
      "id": "5",
      "name": "VIVO",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "6",
      "name": "VIVO1",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "samsungList":[
    {
      "id": "7",
      "name": "三星",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "8",
      "name": "三星2",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "meizuList":[
    {
      "id": "9",
      "name": "魅族",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "10",
      "name": "魅族2",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "xiaomiList":[
    {
      "id": "11",
      "name": "小米",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "12",
      "name": "小米2",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ],
  "iphoneList":[
    {
      "id": "13",
      "name": "苹果",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
    {
      "id": "14",
      "name": "苹果2",
      "createTime": "2018年08月",
      "purchesMoney":"¥5699",
      "appearance":"直板",
      "color":"黑色,白色,红色,橙色,黄色,蓝色",
      "type":"后置三摄,大屏手机,无线充电,大容量电池,快充手机,2.5D弧面屏,指纹识别,2K屏幕,支持NFC,5G手机",
      "phoneSize":"150.9*75.7*8.3 mm",
      "weight":"194 g",
      "screenSize":"屏幕尺寸",
      "screenMaterial":"屏幕材质",
      "screenBit":"屏幕色数",
      "screenResolution":"屏幕分辨率",
      "pixelDensity":"像素密度",
      "screenFeatures":"屏幕特性",
      "operator":"运营商支持",
      "card":"SIM卡类型",
      "wifi":"WiFi",
      "bluetooth":"蓝牙",
      "system":"操作系统",
      "cpuType":"CPU型号",
      "cpuProcess":"CPU制程",
      "runMemory":"运行内存",
      "storageCapacity":"机身容量",
      "rearCamera":"后置相机",
      "frontCamera":"前置相机",
      "zoom":"光学变焦",
      "videoCapture":"视频拍摄",
      "camera":"相机特性",
      "sensor":"感应器",
      "function":"特色功能",
      "usbInterface":"USB接口",
      "headset":"耳机",
      "packing":"包装清单",
    },
  ]
}
